spring:
  application:
    name: spring_boot_demo

  datasource:
    url: ${datasource_url} #variabile di ambiente
    username: sa
    password: sa
    driver-class-name: org.h2.Driver #h2: tipo di DB che lavora su RAM, temporaneo

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active:

jwt:
  secretKey: NGE2YzQ3Njg2OTY5NmJlMWU4YjdmYWFmOTQ5YWE1ZDdhYjUzZjJhMjczZDZjMzM5MTY1YTE5YjEyNjU3OGM2ZTMwYWZkOGQ0YTYyMDc2MDBhOTcxYmNjNGM0NGUwZTQ2

server:
  port: 8086